# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBXQujHAT7nJCB6PClcomwIWtr0QyKrc
"""

pip install paho-mqtt==1.6.0

import paho.mqtt.client as mqtt
client=mqtt.Client()
client.connect("broker.hivemq.com",1883)
client.publish("cse/sdp","Madhu here...")
print("Msg published")

import paho.mqtt.client as mqtt
client=mqtt.Client()
client.connect("broker.hivemq.com",1883)
client.subscribe("cse/sdp")

def notification(client,userdata,msg):
  print(msg.payload)

client.on_message=notification
client.loop_forever()